#170947607 Users should be able to view and edit their profiles
Stackup-Rwanda/knights-bn-frontend pull request #27
Opened 2020-05-10 10:54 UTC by Niyonsengaeric

## ## What does this PR do?

- Users should be able to view and edit their profiles

#### Description of Task to be completed?

- allow the user to view his profile
- allow a user to edit his profile

#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-05-13 07:46 UTC, Kagorora reviewed
Please fix the above feedback and the following:

- On my Profile Form

1. The photo looks odd and if you could put aside the change Picture Button on the right of the picture.

<img width="215" alt="Screen Shot 2020-05-13 at 09 37 21" src="https://user-images.githubusercontent.com/48021034/81785510-b1929880-94fe-11ea-85cb-9bda05fe914c.png">


2. Gender is not being able to be updated

3. Use the calendar to choose the birthday

2020-05-13 07:46 UTC, Kagorora commented on src/components/combo.js
> +// export default ComboBox;
Remove commented file

2020-05-13 07:46 UTC, Kagorora commented on __tests__/redux/reducer/userReducer.test.js
> +  // ============================================================================
remove comments

2020-05-13 07:49 UTC, Kagorora commented on src/views/Profile.js
> +    console.log('_________updated info__________>>>>', result.user);
Remember to remove commented lines

2020-05-13 12:44 UTC, EugeneMunya approved these changes

2020-05-13 18:30 UTC, Kagorora commented
@Niyonsengaeric   Check the following

1. Date(DOB) format, There is additional values that are not needed && CONSIDER USING THE CALENDAR for a better expirience.

<img width="257" alt="Screen Shot 2020-05-13 at 20 27 38" src="https://user-images.githubusercontent.com/48021034/81850426-3bbb1b00-9558-11ea-8112-63e082a36ee4.png">


2. There is a duplication while choosing gender
<img width="234" alt="Screen Shot 2020-05-13 at 20 22 32" src="https://user-images.githubusercontent.com/48021034/81850163-e67f0980-9557-11ea-994c-a57796944c46.png">

2020-05-14 10:39 UTC, Kagorora approved these changes

2020-05-19 15:33 UTC, kagabof requested changes
This file is too large src/views/Profile.js

2020-05-20 14:47 UTC, kagabof approved these changes

2020-05-20 14:47 UTC, merged