#170947627: As a travelAdmin or a Pre screened suppliers I should be able to create Accommodation
Stackup-Rwanda/knights-bn-frontend pull request #32
Opened 2020-05-21 14:40 UTC by Kagorora

#### What does this PR do?

- Will allow Travel Admin or Pre Pre-screened suppliers to create or add accommodation to the system.

#### Description of Task to be completed?

- [ ] Design the mockup

- [ ] Design the UI

- [ ] Validate Inputs

- [ ] Add Functionality to create accommodation

- [ ] Test endpoint

#### How should this be manually tested?

- Clone the project

       git clone https://github.com/Stackup-Rwanda/knights-bn-frontend.git

- Move to the branch

       git checkout ft-create-Accommodation-170947627

-  Install dependencies

       npm install

-  start the server

       npm run dev-start 

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#170947632](https://www.pivotaltracker.com/story/show/170947632)

#### Screenshots (if appropriate)

 MOCKUP

<img width="1440" alt="Screen Shot 2020-05-21 at 16 37 03" src="https://user-images.githubusercontent.com/48021034/82570228-991b2180-9b81-11ea-9088-9e4b278cbcca.png">

#### Questions:

- N/A

2020-05-26 12:15 UTC, Niyonsengaeric reviewed
@Kagorora adds the travel admin credentials.

- it is not working
<img width="1436" alt="Screen Shot 2020-05-26 at 14 12 21" src="https://user-images.githubusercontent.com/50768983/82899275-ff75ba80-9f5a-11ea-8354-6770399fc183.png">

- consider also some code climate issues!!

2020-05-28 10:52 UTC, Niyonsengaeric approved these changes

2020-05-28 10:53 UTC, T2Wil approved these changes
Nice work

2020-05-28 11:45 UTC, kagabof requested changes

2020-05-28 11:45 UTC, kagabof commented on src/components/Nav.js
> +  const tokenForTesting = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0cmF2ZWxhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoidHJhdmVsYWRtaW4iLCJmaXJzdE5hbWUiOiJ0cmF2ZWxlciIsImxhc3ROYW1lIjoiSGltYmF
Why are we having this token?

2020-05-28 11:45 UTC, kagabof commented on src/components/NavSupplier.js
> +const NavAuth = () => {
You should fix this.

2020-05-29 09:42 UTC, kagabof commented
Please check your test logs.

2020-05-29 13:32 UTC, kagabof approved these changes

2020-05-29 13:32 UTC, merged