Approvals Table
Stackup-Rwanda/knights-bn-frontend pull request #33
Opened 2020-05-23 09:34 UTC by Niyonsengaeric

#### What does this PR do?
- allow a user(administrator) to see a list of requests that require his/her approval on the Approvals page.
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-05-26 08:32 UTC, T2Wil commented
Nice work @Niyonsengaeric ,
Here are few feedback :
1. I don't think these first two columns should be displayed

![image](https://user-images.githubusercontent.com/30593186/82878542-e90c3680-9f3b-11ea-87d7-202c0eda3e77.png)

2. When I `as a manager` approve/reject the request the page should refresh with new data.

2020-05-26 08:34 UTC, Kagorora commented
@Niyonsengaeric , Good Job
Here are my feedback
1. Fix the code climate issues
2. The table has too may information, could you reduce the columns that are in the table
and only remain with the necessary ones
3. Actions, accept or reject should be inline(not on top of the other)

2020-05-27 06:39 UTC, T2Wil approved these changes
Nice work @Niyonsengaeric

2020-05-27 07:49 UTC, Kagorora commented
@Niyonsengaeric , Could you use Bootstrap Modal or anyother to ask for comfirmation, this default alert does not LGTM.

<img width="579" alt="Screen Shot 2020-05-27 at 09 48 06" src="https://user-images.githubusercontent.com/48021034/82992379-5c2ab100-9fff-11ea-924f-67b029286e7c.png">

2020-05-27 08:40 UTC, Kagorora approved these changes

2020-05-27 09:43 UTC, kagabof commented on src/redux/actions/requestActions.js
> +import * as types from './actionTypes';
Please check this error.

2020-05-27 09:44 UTC, kagabof commented on src/redux/reducers/requestReducer.js
> +import * as types from '../actions/actionTypes';
Please check this error.

2020-05-27 09:45 UTC, kagabof commented on src/components/TableData.js
> +import React from 'react';
Please check this error.

2020-05-27 09:45 UTC, kagabof commented on src/components/TableData.js
> +      <td><a href="#" className="text-success" onClick={() => {
Please check this error.

2020-05-27 09:45 UTC, kagabof commented on src/components/TableData.js
> +      <a href="#" className="text-danger" onClick={() => {
Please check this error.

2020-05-27 09:46 UTC, kagabof commented on src/util/userRole.js
> +import jwt from 'jsonwebtoken';
Please check this error.

2020-05-27 09:47 UTC, kagabof commented on src/views/PendingRequests.js
> +export const PendingRequest = (props) => {
Please check this error.

2020-05-27 09:47 UTC, kagabof commented on src/redux/reducers/requestReducer.js
> +const reduce = (state, action) => {
Please check this error.

2020-05-27 09:47 UTC, kagabof commented on src/views/PendingRequests.js
> +export const PendingRequest = (props) => {
Please check this error.

2020-05-27 09:54 UTC, kagabof requested changes

2020-05-27 09:54 UTC, kagabof commented on src/components/TableData.js
> +import React from 'react';
Please check this error.

2020-05-27 09:54 UTC, kagabof commented on src/components/TableData.js
> +      <td><a href="#" className="text-success" onClick={() => {
Please check this error.

2020-05-27 09:54 UTC, kagabof commented on src/redux/actions/requestActions.js
> +import * as types from './actionTypes';
Please check this error.

2020-05-27 09:54 UTC, kagabof commented on src/redux/reducers/requestReducer.js
> +const reduce = (state, action) => {
Please check this error.

2020-05-27 09:54 UTC, kagabof commented on src/util/userRole.js
> +import jwt from 'jsonwebtoken';
Please check this error.

2020-05-27 12:58 UTC, Niyonsengaeric commented on src/components/TableData.js
> +import React from 'react';
this file is also outdated maybe there is an issue with codeclimate!

2020-05-27 14:01 UTC, kagabof approved these changes
Well done.

2020-05-27 14:02 UTC, merged